<template>
  <div class="vld-parent">
    <loading :active="isLoading" :can-cancel="true"  :is-full-page="true" :color="'#43342F'">
      <div class="loadingio-spinner-spin-nwqkzohoq6o"><div class="ldio-6grgxnrkcz">
        <div><div></div></div><div><div></div></div><div><div></div></div><div><div></div></div><div><div></div></div><div><div></div></div><div><div></div></div><div><div></div></div>
      </div></div>
    </loading>
  </div>
</template>

<script>
// Import component
import Loading from 'vue-loading-overlay';
// Import stylesheet
import 'vue-loading-overlay/dist/vue-loading.css';
export default {
  data () {
    return {
      isLoading: false
    };
  },
  components: {
    Loading
  },
  methods: {
    doAjax () {
      this.isLoading = true;
    },
    timeIsOut () {
      this.isLoading = false;
    }
  }
};
</script>

<style type="text/css">
@keyframes ldio-6grgxnrkcz {
  0% {
    opacity: 1;
    backface-visibility: hidden;
    transform: translateZ(0) scale(1.5,1.5);
  } 100% {
    opacity: 0;
    backface-visibility: hidden;
    transform: translateZ(0) scale(1,1);
  }
}
.ldio-6grgxnrkcz div > div {
  position: absolute;
  width: 24.36px;
  height: 24.36px;
  border-radius: 50%;
  background: #627364;
  animation: ldio-6grgxnrkcz 0.9174311926605504s linear infinite;
}.ldio-6grgxnrkcz div:nth-child(1) > div {
  left: 150.5px;
  top: 89.49999999999999px;
  animation-delay: -0.8027522935779816s;
}
.ldio-6grgxnrkcz > div:nth-child(1) {
  transform: rotate(0deg);
  transform-origin: 162.68px 101.67999999999999px;
}.ldio-6grgxnrkcz div:nth-child(2) > div {
  left: 132.5px;
  top: 132.5px;
  animation-delay: -0.6880733944954128s;
}
.ldio-6grgxnrkcz > div:nth-child(2) {
  transform: rotate(45deg);
  transform-origin: 144.68px 144.68px;
}.ldio-6grgxnrkcz div:nth-child(3) > div {
  left: 89.49999999999999px;
  top: 150.5px;
  animation-delay: -0.573394495412844s;
}
.ldio-6grgxnrkcz > div:nth-child(3) {
  transform: rotate(90deg);
  transform-origin: 101.67999999999999px 162.68px;
}.ldio-6grgxnrkcz div:nth-child(4) > div {
  left: 46.499999999999986px;
  top: 132.5px;
  animation-delay: -0.4587155963302752s;
}
.ldio-6grgxnrkcz > div:nth-child(4) {
  transform: rotate(135deg);
  transform-origin: 58.67999999999999px 144.68px;
}.ldio-6grgxnrkcz div:nth-child(5) > div {
  left: 28.499999999999986px;
  top: 89.49999999999999px;
  animation-delay: -0.3440366972477064s;
}
.ldio-6grgxnrkcz > div:nth-child(5) {
  transform: rotate(180deg);
  transform-origin: 40.67999999999999px 101.67999999999999px;
}.ldio-6grgxnrkcz div:nth-child(6) > div {
  left: 46.499999999999986px;
  top: 46.499999999999986px;
  animation-delay: -0.2293577981651376s;
}
.ldio-6grgxnrkcz > div:nth-child(6) {
  transform: rotate(225deg);
  transform-origin: 58.67999999999999px 58.67999999999999px;
}.ldio-6grgxnrkcz div:nth-child(7) > div {
  left: 89.49999999999999px;
  top: 28.499999999999986px;
  animation-delay: -0.1146788990825688s;
}
.ldio-6grgxnrkcz > div:nth-child(7) {
  transform: rotate(270deg);
  transform-origin: 101.67999999999999px 40.67999999999999px;
}.ldio-6grgxnrkcz div:nth-child(8) > div {
  left: 132.5px;
  top: 46.499999999999986px;
  animation-delay: 0s;
}
.ldio-6grgxnrkcz > div:nth-child(8) {
  transform: rotate(315deg);
  transform-origin: 144.68px 58.67999999999999px;
}
.loadingio-spinner-spin-nwqkzohoq6o {
  width: 203px;
  height: 203px;
  display: inline-block;
  overflow: hidden;
  background: none;
}
.ldio-6grgxnrkcz {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-6grgxnrkcz div { box-sizing: content-box; }
/* generated by https://loading.io/ */
</style>
